package com.github.aquamancer.warlordsbufficons.statuses;

public enum Buff {
    NONE,
    
    TIME_WARP,
    ARCANE_SHIELD,
    INFERNO,
    ICE_BARRIER,
    // ANTI_KB cryo time warp boost
    HEALING_RAIN,
    SPEED_CLAIRVOYANCE,
    // HEALING_RAIN_ACTIVE
    
    BLOOD_LUST,
    BERSERK,
    INTERVENE_OUTGOING,
    INTERVENE_INCOMING,
    LAST_STAND_OUTGOING,
    LAST_STAND_INCOMING,
    RECKLESS_CHARGE_DAMAGE_REDUCTION,
    HEALING_LINK_OUTGOING,
    ORBS_OF_LIFE,
    UNDYING_ARMY,
    UNDYING_STEED
}
